[package]
name = "profiling-procmacros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro=true
